import { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { courts, openGames } from '@/data/mockData';
import { colors, spacing } from '@/theme/tokens';
import { SearchBar } from '@/components/common/SearchBar';
import { FilterChips } from '@/components/common/FilterChips';
import { ImageWithFallback } from '@/components/common/ImageWithFallback';
import { PremiumButton } from '@/components/common/PremiumButton';

export default function Courts(){const [q,setQ]=useState('');const [f,setF]=useState<string[]>([]);const [modal,setModal]=useState(''); const filtered=useMemo(()=>courts.filter(c=>(c.name+c.area).toLowerCase().includes(q.toLowerCase())&& (f.length===0 || f.some(x=>x==='Indoor'?c.indoor:x==='Outdoor'?!c.indoor:c.area===x))),[q,f]);
return <ScrollView style={s.wrap} contentContainerStyle={{padding:spacing.md,gap:14}}><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{courts.slice(0,4).map(c=><Pressable key={c.id} onPress={()=>router.push(`/court/${c.id}`)}><ImageWithFallback uri={c.image} style={s.hero}/><Text style={s.heroT}>Find a padel court in Qatar</Text><Text style={s.heroS}>Book externally, create ranked matches, and climb the Qatar leaderboard.</Text></Pressable>)}</ScrollView><SearchBar value={q} onChangeText={setQ}/><FilterChips items={['Tonight','Indoor','Outdoor','Lusail','Katara','Msheireb','The Pearl','Aspire']} active={f} onToggle={(x)=>setF(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}/><Text style={s.h}>Available Tonight</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{filtered.map(c=><Pressable key={c.id} style={s.card} onPress={()=>router.push(`/court/${c.id}`)}><ImageWithFallback uri={c.image} style={s.img}/><Text style={s.n}>{c.name}</Text><Text style={s.meta}>{c.area} • {c.indoor?'Indoor':'Outdoor'}</Text><Text style={s.meta}>{c.timeSlots.join(' · ')}</Text><View style={{flexDirection:'row',gap:8,marginTop:8}}><PremiumButton label='Book externally' onPress={()=>setModal(`Booking link for ${c.name}`)} secondary/><PremiumButton label='Start ranked match' onPress={()=>setModal(`Ranked match flow at ${c.name}`)}/></View></Pressable>)}</ScrollView><Text style={s.h}>Open Games Near You</Text>{openGames.slice(0,4).map(g=><View key={g.id} style={s.row}><Text>Game at {courts.find(c=>c.id===g.courtId)?.name}</Text><PremiumButton label='Join' onPress={()=>setModal('Request sent to host')}/></View>)}<Modal visible={!!modal} transparent animationType='slide'><Pressable style={s.backdrop} onPress={()=>setModal('')}><View style={s.sheet}><Text style={{fontWeight:'700'}}>{modal}</Text></View></Pressable></Modal></ScrollView>}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:colors.background},hero:{width:340,height:220,borderRadius:20,marginRight:12},heroT:{position:'absolute',bottom:54,left:14,color:'#fff',fontWeight:'800',fontSize:22},heroS:{position:'absolute',bottom:16,left:14,right:14,color:'#fff'},h:{fontSize:20,fontWeight:'800',color:colors.textPrimary},card:{width:320,backgroundColor:'#fff',padding:10,borderRadius:16,marginRight:12},img:{height:140,borderRadius:12},n:{fontWeight:'800',marginTop:8},meta:{color:colors.textSecondary,marginTop:4},row:{backgroundColor:'#fff',padding:12,borderRadius:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:8},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.3)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',padding:20,borderTopLeftRadius:20,borderTopRightRadius:20}})
