import { useEffect, useMemo, useRef, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { BlurView } from 'expo-blur';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { MotiView } from 'moti';
import { courts, openGames } from '@/data/mockData';
import { colors } from '@/theme/tokens';
import { SearchBar } from '@/components/common/SearchBar';
import { FilterChips } from '@/components/common/FilterChips';
import { ImageWithFallback } from '@/components/common/ImageWithFallback';
import { PremiumButton } from '@/components/common/PremiumButton';

export default function Courts() {const [q,setQ]=useState('');const [f,setF]=useState<string[]>([]);const [sheet,setSheet]=useState<{type:'book'|'ranked',name:string}|null>(null);const heroRef=useRef<ScrollView>(null);const [idx,setIdx]=useState(0);
useEffect(()=>{const i=setInterval(()=>{const n=(idx+1)%3;setIdx(n);heroRef.current?.scrollTo({x:n*360,animated:true});},3500);return()=>clearInterval(i);},[idx]);
const filtered=useMemo(()=>courts.filter(c=>(`${c.name} ${c.area}`.toLowerCase().includes(q.toLowerCase()))&&(f.length===0||f.some(x=>x==='Indoor'?c.indoor:x==='Outdoor'?!c.indoor:c.area.includes(x)))),[q,f]);
return <ScrollView style={s.w} contentContainerStyle={{padding:14,gap:16}}><ScrollView ref={heroRef} horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{courts.slice(0,3).map(c=><Pressable key={c.id} onPress={()=>router.push(`/court/${c.id}`)} style={s.heroWrap}><ImageWithFallback uri={c.image} style={s.hero}/><LinearGradient colors={['transparent','rgba(26,16,21,0.8)']} style={s.g}/><Text style={s.ht}>Find a padel court in Qatar</Text><Text style={s.hs}>Book externally, open ranked games, and climb the Qatar leaderboard.</Text></Pressable>)}</ScrollView><SearchBar value={q} onChangeText={setQ}/><FilterChips items={['Tonight','Indoor','Outdoor','Lusail','Katara','Msheireb','Education City','Aspire']} active={f} onToggle={(x)=>setF(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}/><Text style={s.h}>Available tonight</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{filtered.map(c=><MotiView key={c.id} from={{opacity:0,translateY:8}} animate={{opacity:1,translateY:0}} style={s.card}><Pressable onPress={()=>router.push(`/court/${c.id}`)}><ImageWithFallback uri={c.image} style={s.img}/><Text style={s.n}>{c.name}</Text><Text style={s.m}>{c.area} • {c.indoor?'Indoor':'Outdoor'}</Text><View style={s.ts}>{c.timeSlots.map(t=><Text key={t} style={s.tc}>{t}</Text>)}</View><View style={s.am}>{['car','coffee','wifi'].map(i=><MaterialCommunityIcons key={i} name={i as any} size={16} color={colors.primary}/>)}</View></Pressable><View style={s.br}><View style={{flex:1}}><PremiumButton label='Book externally' onPress={()=>setSheet({type:'book',name:c.name})} variant='secondary'/></View><View style={{flex:1}}><PremiumButton label='Start ranked match' onPress={()=>setSheet({type:'ranked',name:c.name})}/></View></View></MotiView>)}</ScrollView><Text style={s.h}>Open games near you</Text><ScrollView horizontal>{openGames.map(g=><View key={g.id} style={s.open}><Text style={{fontWeight:'700'}}>{courts.find(c=>c.id===g.courtId)?.name}</Text><Text style={{color:colors.textSecondary}}>{g.date}</Text></View>)}</ScrollView><Modal visible={!!sheet} transparent animationType='slide'><Pressable style={s.back} onPress={()=>setSheet(null)}><BlurView intensity={20} style={s.sheet}><Text style={s.h}>{sheet?.name}</Text>{sheet?.type==='book'?<><PremiumButton label='Open Playtomic' onPress={()=>setSheet(null)}/><PremiumButton label='Club Website' onPress={()=>setSheet(null)} variant='secondary'/><PremiumButton label='Call Club' onPress={()=>setSheet(null)} variant='subtle'/></>:<><PremiumButton label='Invite players' onPress={()=>setSheet(null)}/><PremiumButton label='Open game' onPress={()=>setSheet(null)} variant='secondary'/><PremiumButton label='Submit result later' onPress={()=>setSheet(null)} variant='subtle'/></>}</BlurView></Pressable></Modal></ScrollView>}
const s=StyleSheet.create({w:{flex:1,backgroundColor:'#F7F3F0'},heroWrap:{width:360,height:280,marginRight:10},hero:{width:'100%',height:'100%',borderRadius:22},g:{position:'absolute',left:0,right:0,bottom:0,height:140,borderRadius:22},ht:{position:'absolute',left:16,bottom:58,color:'#fff',fontWeight:'800',fontSize:28},hs:{position:'absolute',left:16,right:16,bottom:20,color:'#fff'},h:{fontSize:22,fontWeight:'800',color:'#171014'},card:{width:320,backgroundColor:'#fff',borderRadius:18,padding:12,marginRight:10},img:{height:170,borderRadius:14},n:{fontWeight:'800',fontSize:17,marginTop:8},m:{color:'#6F666B',marginTop:4},ts:{flexDirection:'row',gap:8,marginTop:8},tc:{backgroundColor:'#f3e8ee',paddingHorizontal:10,paddingVertical:5,borderRadius:20,color:'#660033'},am:{flexDirection:'row',gap:8,marginTop:8},br:{flexDirection:'row',gap:8,marginTop:10},open:{width:220,padding:12,backgroundColor:'#fff',borderRadius:12,marginRight:8},back:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.35)'},sheet:{padding:20,backgroundColor:'#fff',borderTopLeftRadius:20,borderTopRightRadius:20,gap:10}})
