import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { players } from '@/data/mockData';
import { colors, spacing } from '@/theme/tokens';
const filters=['All','Beginner','Intermediate','Advanced','This Week'] as const;
export default function Leaderboard(){const [filter,setFilter]=useState<typeof filters[number]>('All'); const shown=players.filter(p=>filter==='All'||filter==='This Week'||p.level===filter);
return <ScrollView style={styles.s} contentContainerStyle={{padding:spacing.lg}}><Text style={styles.t}>Qatar Top 100</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginBottom:12}}>{filters.map(f=><TouchableOpacity key={f} onPress={()=>setFilter(f)} style={[styles.chip,filter===f&&styles.active]}><Text style={[styles.chipT,filter===f&&styles.activeT]}>{f}</Text></TouchableOpacity>)}</ScrollView><View style={styles.podium}><Text style={styles.podiumT}>🥇 {shown[0]?.name} • {shown[0]?.rating}</Text><Text style={styles.podiumT}>🥈 {shown[1]?.name}</Text><Text style={styles.podiumT}>🥉 {shown[2]?.name}</Text></View>{shown.map(p=><TouchableOpacity key={p.id} onPress={()=>router.push(`/player/${p.id}`)} style={styles.row}><Text style={styles.rank}>#{p.rank}</Text><View style={{flex:1}}><Text style={styles.n}>{p.name} {p.movement>0?`↑${p.movement}`:`${p.movement}`}</Text><Text style={styles.meta}>{p.username} • {p.wins}-{p.losses} • {Math.round(p.wins/(p.wins+p.losses)*100)}% • {p.verified?'Verified':''}</Text></View><Text style={styles.r}>{p.rating}</Text></TouchableOpacity>)}</ScrollView>}
const styles = StyleSheet.create({s:{flex:1,backgroundColor:colors.background},t:{color:colors.text,fontSize:28,fontWeight:'800',marginBottom:12},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:20,backgroundColor:colors.surfaceAlt,marginRight:8},active:{backgroundColor:colors.gold},chipT:{color:colors.sand},activeT:{color:'#201607',fontWeight:'700'},podium:{backgroundColor:colors.card,padding:16,borderRadius:16,borderColor:colors.gold,borderWidth:1,marginBottom:12},podiumT:{color:colors.text,paddingVertical:2},row:{flexDirection:'row',paddingVertical:10,borderBottomColor:colors.border,borderBottomWidth:1},rank:{color:colors.gold,width:44,fontWeight:'700'},n:{color:colors.text,fontWeight:'600'},meta:{color:colors.muted,fontSize:12},r:{color:colors.sand,fontWeight:'700'}});
